### ISSUE TITLE
Some schema issue discovered...

### ISSUE THREAD

**Issue by drsharp** [ifp/schemas#5]
Here are a few issues that maybe should be resolved with the schema... or with my code:

1. `feed_urls` => this is currently type `Array`, but there is only _one_ mapper that has multiple feeds. Should it instead be type `String` and just concatenate the feeds for that one mapper (Coast and Country)? What is the expectation for how this field would be used?

2. `created_at` & `updated_at` => If a feed doesn't map these, they'll be `null` in the JSON, but the schema doesn't allow Null values.

3. Similarly, `dpe letter` and `ges letter` could be `null` if a feed doesn't have them at all. Should the schema allow Null? I don't think it makes sense to have a default value, but we could add that if it does.

4. `update_conflicts` => this is type `Object` but I don't know how to return that type in the advert importer code. Of course, the advert importer code doesn't do anything with it, so maybe it should just allow `null` and I can return it as null.

**Comment by ifpingram** [comment]
Hi Dan

1. feed_urls - is this a pain your side to keep it as an array? I really do
not like the idea of concatenating them into a string. We actually have a
couple more agents using this approach, and yet to integrate, so there will
be a small need for it beyond Coast & Country. These are purely for
reference and debugging, so that we can quickly view the feed which the
advert came from. Ideally in future, we would want to show the saved feed
from the import, as opposed to the "live" url of the feed. Is this
possible? Do we yet save these feeds somewhere?

2. Good spot! Nulls now allowed in both fields.

3. The dpe and ges letters both allow null - where are you seeing it is not
in the schema? We can't have a default value; it is A-G or null only.

4. Have added null to update_conflicts for you to always return.

Cheers

Ing

**Comment by drsharp** [comment]
Hi Ingram!

#1 - that's fine. It's not really that much of a pain, actually. I just thought C&C was the _only_ one. No worries. Also, yes, the Archiver step FTPs the feed (or feeds) to Exavault. So we can certainly make those feeds available at some point.

#3 - I wonder if what's happening is that because there weren't any DPE or GES values in the particular feed I was checking (not sure which at the moment, but that doesn't matter), maybe it wasn't even like `"dpe_letter":null` in the JSON but simply wasn't there at all. In other words, according to the schema the dpe_letter and ges_letter must be present in the JSON, but is allowed to have a null value. I'll take care of it.

I'll create an issue for each of these two.

Cheers!
